
# Filter BLAST output based on homology
cat blast.out.tsv | awk '($4-$5)/30 >= 0.85' > blast.out.85percHom.tsv

# Make oligo_seq|hit_transcriptID table
cat 30mer.uniq.filter.40_70_gc.noHpol.fa | paste - - | sed 's/.//' | join -j 1 -t $'\t' - <(cat blast.out.85percHom.tsv) -o 1.2,2.2 | sed 's/\.[0-9]*$//' > blast.out.85percHom.transcripts.txt

# Identify transcripts
cut -f 2 blast.out.85percHom.transcripts.txt | sort | uniq

# Retrieve transcript gene symbol
cat transcript_list.txt | join -j 1 -t $'\t' - <(cat human_gene_symbol_tr_id_table.kf.tsv | sort -k1) > transcript_gene_list.txt

# Make oligo_seq|hit_transcriptID|Gene_Symbol table
cat blast.out.85percHom.transcripts.txt | sort -k2 | join -1 2 -2 1 - <(cat transcript_gene_list.txt) -t $'\t' -o 1.1,1.2,2.2 | sort -k1 --paralle 40 -S10G > blast.out.85percHom.transcripts.gene.txt



##########################################################################



# blastn -db /media/gire/Data/BiCro-Resources/references/Grch38_89_cdna_ncrna/Grch38.89.cdna.ncrna -query /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_uniq_filtered/30mer.uniq.filter.30_70_gc.noHpol.fa -outfmt 6 -out /home/gire/Desktop/30mer.uniq.filter.30_70_gc.noHpol.blast.out.tsv -word_size 10 -num_threads 35 -penalty -2 -reward 3 -gapopen 100 -gapextend 100 -evalue 1000 -strand plus

# Filter BLAST output based on homology with more relaxed threshold
cat blast.out.tsv | awk '($4-$5)/30 >= 0.7' > blast.out.70percHom.tsv
sort -k1,1 --parallel 30 -S20G blast.out.70percHom.tsv > blast.out.70percHom.sorted.tsv

# Make GC|homPerc|oligo_seq|hit_transcriptID table
cat 30mer.uniq.filter.40_70_gc.noHpol.fa | paste - - | sed 's/^.//' | sort -k1,1 | join -j 1 -t $'\t' - <(cat 30mer.uniq.filter.40_70_gc.noHpol.blast.out.70percHom.sorted.tsv) -o 1.1,1.2,2.2,2.4,2.5 | awk -v k=30 '{OFS=FS="\t"; split($1, ff, ":"); split($3, gg, "."); print ff[2]"\t"($4-$5)/k"\t"$2"\t"gg[1]}' | sed 's/\.[0-9]*$//' > 30mer.uniq.filter.40_70_gc.noHpol.blast.out.70percHom.transcripts.tsv

# Make GC|homPerc|oligo_seq|hit_transcriptID|Gene_Symbol table
cat blast.out.85percHom.transcripts.txt | sort -k4,4 -S10G --parallel 35 | join -1 4 -2 1 - <(cat transcript_gene_list.txt) -t $'\t' -o 1.1,1.2,1.3,1.4,2.2 | sort -k3 --parallel 35 -S10G > blast.out.85percHom.transcripts.gene.txt

# Filter for more restrictive homology levels
blast.out.70percHom.transcripts.gene.tsv | awk '$2 >= 0.75' > blast.out.75percHom.transcripts.gene.tsv
blast.out.75percHom.transcripts.gene.tsv | awk '$2 >= 0.80' > blast.out.80percHom.transcripts.gene.tsv
blast.out.80percHom.transcripts.gene.tsv | awk '$2 >= 0.80' > blast.out.85percHom.transcripts.gene.tsv

# Remove first two columns
cut -f 3-5 blast.out.70percHom.transcripts.gene.tsv > blast.out.70percHom.transcripts.gene.clean.tsv
cut -f 3-5 blast.out.75percHom.transcripts.gene.tsv > blast.out.75percHom.transcripts.gene.clean.tsv
cut -f 3-5 blast.out.80percHom.transcripts.gene.tsv > blast.out.80percHom.transcripts.gene.clean.tsv
cut -f 3-5 blast.out.85percHom.transcripts.gene.tsv > blast.out.85percHom.transcripts.gene.clean.tsv

# Run blast_filter_parallel
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.40_60gc.85homPerc.20ot.5sl -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.40_60gc.85homPerc.20ot.5sl -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.40_60gc.85homPerc.20ot.5sl -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.40_70gc.85homPerc.20ot.5sl -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.40_70gc.85homPerc.20ot.5sl -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.40_70gc.85homPerc.20ot.5sl -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.30_70gc.85homPerc.20ot.5sl -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.30_70gc.85homPerc.20ot.5sl -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.30_70gc.85homPerc.20ot.5sl -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.40_60gc.85homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.40_60gc.85homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.40_60gc.85homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.40_70gc.85homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.40_70gc.85homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.40_70gc.85homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.30_70gc.85homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.30_70gc.85homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.85percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.30_70gc.85homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.80percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.40_60gc.80homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.80percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.40_60gc.80homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.80percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.40_60gc.80homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.80percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.40_70gc.80homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.80percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.40_70gc.80homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.80percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.40_70gc.80homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.80percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.30_70gc.80homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.80percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.30_70gc.80homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.80percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.30_70gc.80homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.75percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.40_60gc.75homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.75percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.40_60gc.75homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.75percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.40_60gc.75homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.75percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.40_70gc.75homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.75percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.40_70gc.75homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.75percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.40_70gc.75homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.75percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.30_70gc.75homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.75percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.30_70gc.75homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.75percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.30_70gc.75homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.70percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.40_60gc.70homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.70percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.40_60gc.70homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.70percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.40_60gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.40_60gc.70homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.70percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.40_70gc.70homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.70percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.40_70gc.70homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.70percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.40_70gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.40_70gc.70homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.70percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cds.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cds.30_70gc.70homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.70percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/cdna.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/cdna.30_70gc.70homPerc.1ot.1sl -s 1 -g 1 -t 35
$REPO/potpourri/680-genes-fish-oligos/blast_filter/parallel_blast_filter.sh -i /media/gire/Data/BiCro-Analysis/Sequencing/680genes/blast/30mer.uniq.filter.30_70_gc.noHpol.blast.out.70percHom.transcripts.gene.clean.tsv -y /home/gire/Desktop/BiCro/External_mounts/Fileserver1/sequencing_data/680_genes_project/databases/2017-07-21-COSMIC_Testa_Lundeberg_gene_list.fixed.tsv -f /media/gire/Data/BiCro-Analysis/Sequencing/680genes/oligo_filtered_by_gene/exon.30_70gc -o /home/gire/Desktop/blast_filtered_by_gene/exon.30_70gc.70homPerc.1ot.1sl -s 1 -g 1 -t 35
